CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_REPORT_INTERVAL_MIN=8

# Enable ZMK Pointing processors
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_INPUT_PROCESSOR_SCALER=y
CONFIG_ZMK_INPUT_PROCESSOR_XY_TO_SCROLL_MAPPER=y
CONFIG_ZMK_INPUT_PROCESSOR_SCROLL_TRANSFORM=y